---
title: "analysis"
author: "Joshua Rosenberg"
date: "9/13/2018"
output:
  html_document:
    number_sections: yes
    toc: yes
    toc_depth: 2
  pdf_document:
    toc: yes
    toc_depth: '2'
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

# Loading, setting up

In this section, we start out by doing:

```{r, load-packages, message = FALSE}
library(tidyverse)
library(corrr)
library(broom)
library(patchwork) # devtools::install_github("thomasp85/patchwork")
usethis::use_git_ignore("*.csv")
```

Read the data:

```{r, load-data, eval = TRUE}
d <- read_csv("full-tetcs-dataset.csv")
d <- d %>% slice(-c(1:2))
```

Check that the data loaded:

```{r, check-that-data-loaded}
d
```

Process the TETCs variables:

```{r}
ds <- d %>% 
    select(Q11_1:Q11_12) %>% 
    set_names(1:12) %>% 
    mutate_all(str_extract, "\\(?[0-9,.]+\\)?") %>% 
    mutate_all(as.integer) %>% 
    set_names(str_c("v", 1:12))

ds %>% 
    summarize_all(funs(mean, sd), na.rm = TRUE) %>%
    gather(key, val) %>% 
    separate(key, into = c("var", "stat")) %>% 
    spread(stat, val) %>% 
    mutate(TETC = str_sub(var, start = 2),
           TETC = as.integer(TETC)) %>% 
    arrange(TETC) %>% 
    mutate(TETC = str_c("TETC", TETC)) %>% 
    mutate(mean = round(mean, 3),
           sd = round(sd, 3)) %>% 
    mutate(mean_sd = str_c(mean, " (", sd, ")")) %>% 
    select(mean_sd)

c <- cbind(ds)

g <- ds %>% 
    gather(key, val)

summary(aov(val ~ key, g))
```

# RQ1: TETC Levels

```{r}
dss <- ds %>% 
    gather(key, val) %>% 
    mutate(key = str_replace(key, "v", "TETC-"))

dss$key = with(dss, reorder(key, val, mean, na.rm = TRUE))

summary(aov(val~key, data = dss))

dd <- ds %>% 
    gather(key, val) %>% 
    mutate(key = str_replace(key, "v", "TETC-")) %>% 
    mutate(key = factor(key, levels = c("TETC-4", "TETC-12", "TETC-3", "TETC-2", "TETC-7", "TETC-6", "TETC-1", "TETC-10", "TETC-5", "TETC-9", "TETC-11", "TETC-8")))

# str_c(round(mean(dd$val, na.rm = TRUE), 3), " (", round(sd(dd$val, na.rm = TRUE), 3), ")")
summary(aov(val ~ key, data = dd))

x <- aov(val ~ key, data = dd)

x %>% 
    TukeyHSD() %>% 
    pluck(1) %>% 
    as.data.frame() %>% 
    rownames_to_column("comparison") %>% 
    select(comparison, `p adj`) %>% 
    as_tibble() %>% 
    mutate_if(is.numeric, round, 3) %>% 
    arrange(comparison) %>% 
    write_csv("TETCs-Tukey-HSD.csv")

dp <- ds %>% 
    gather(key, val) %>% 
    mutate(key = str_replace(key, "v", "TETC-")) %>% 
    group_by(key) %>% 
    summarize(mean_val = mean(val, na.rm = TRUE),
              sd_val = sd(val, na.rm = TRUE)) %>% 
    arrange(desc(mean_val))

ds %>% 
    gather(key, val) %>% 
    mutate(key = str_replace(key, "v", "TETC-")) %>% 
    group_by(key) %>% 
    summarize(mean_val = mean(val, na.rm = TRUE),
              sd_val = sd(val, na.rm = TRUE)) %>% 
    mutate(mean_sd = str_c(round(mean_val, 2), " (", round(sd_val, 2), ")")) %>% 
    select(mean_sd)

dp %>% 
    ggplot() +
    geom_jitter(data = dd, aes(x = reorder(key, val), y = val), alpha = .5, color = "gray") +
    geom_point(aes(x = reorder(key, mean_val), y = mean_val), size = 2.5) +
    geom_errorbar(aes(x = reorder(key, mean_val),
                      ymin = mean_val-sd_val,
                      ymax = mean_val+sd_val)) +
    theme_bw() +
    ylab("Value") +
    xlab(NULL)

ggsave('tetc-plot.png', width = 8, height = 6)
```

# RQ3: Relations of Vars

## Years of experience

```{r}
d <- d %>%
    mutate(Q5_1=as.integer(Q5_1),
           Q5_2=as.integer(Q5_2)) %>% 
    bind_cols(ds)

re_p <- function(x) {
    ifelse(x < .001, "***",
           ifelse(x < .01, "**",
                  ifelse(x < .05, "*",
                         ifelse(x < .10, "+", ""))))
}

ps <- d %>% 
    select(years_teach_exp = Q5_1, 
           yeras_te_exp = Q5_2,
           v1:v12) %>% 
    as.matrix() %>% 
    Hmisc::rcorr() %>% 
    pluck(3) %>% 
    as.data.frame() %>% 
    select(1:2) %>% 
    slice(3:nrow(.)) %>% 
    unlist() %>% 
    p.adjust(method = "hochberg") %>% 
    matrix(ncol = 2) %>% 
    as_tibble() %>%
    set_names(c("years_tch_exp", "years_te_experience")) %>% 
    mutate_all(re_p)

rs <- d %>% 
    select(years_teach_exp = Q5_1, 
           yeras_te_exp = Q5_2,
           v1:v12) %>% 
    as.matrix() %>% 
    Hmisc::rcorr() %>% 
    pluck(1) %>% 
    as.data.frame() %>% 
    select(1:2) %>% 
    slice(3:14) %>% 
    set_names(c("years_tch_exp", "years_te_experience"))

data.frame(v1 = str_c(round(rs$years_tch_exp,2), ps$years_tch_exp),
           v2 = str_c(round(rs$years_te_experience,2), ps$years_te_experience))
```


## Grade level

```{r}
d  %>% 
    count(Q7) %>% 
    arrange(desc(n))%>% 
    write_csv("grade-levels.csv")

m <- read_csv("grade-levels-m.csv")
m <- m %>% set_names(c("Q7", "Q7n", "Q7_code"))

d <- d %>% left_join(m, by = "Q7")

dd <- d %>% select(v1:v12, Q7_code)
c <- cbind(dd[, 1:12])
m <- manova(as.matrix(c) ~ dd$Q7_code)
summary(m)

d %>% 
    select(v1:v12) %>% 
    map(~ aov(. ~ d$Q7_code)) %>% 
    map_df(tidy) %>% 
    filter(term != "Residuals") %>% 
    mutate(var = str_c("v", 1:12)) %>% 
    select(var, sumsq, statistic, p.value) %>% 
    mutate(p.value_adj = p.adjust(p.value, method = "hochberg"))

d %>% 
    select(v1:v12) %>% 
    map(~ aov(. ~ d$Q7_code)) %>% 
    map(TukeyHSD) %>% 
    map_df(tidy) %>% 
    mutate(var = rep(1:12, each = 6)) %>% 
    mutate_if(is.numeric, round, 3) %>% 
    mutate(est_p = ifelse(adj.p.value < .001, str_c(estimate, "***"),
                          ifelse(adj.p.value < .01, str_c(estimate, "**"),
                                 ifelse(adj.p.value < .05, str_c(estimate, "*"), estimate)))) %>%     select(var, comparison, est_p) %>% 
    spread(comparison, est_p) %>%
    write_csv("grade-tukey.csv")

dm <- d %>% 
    select(Q7_code, v1:v12) %>% 
    gather(key, val, -Q7_code)

x <- aov(val ~ Q7_code, data = dm)

TukeyHSD(x) %>% 
    pluck(1) %>% 
    as.data.frame() %>% 
    rownames_to_column("comparison") %>% 
    mutate_if(is.numeric, round, 3)

summary(aov(val ~ Q7_code*key, data = dm))

sg <- d %>% 
    select(Q7_code, v1:v12) %>% 
    gather(key, val, -Q7_code) %>% 
    group_by(Q7_code) %>% 
    summarize(mean = mean(val, na.rm = TRUE),
              sd = sd(val, na.rm = TRUE)) %>% 
    ggplot(aes(x = reorder(Q7_code, mean), y = mean, ymin = mean - ((1.96*sd)/sqrt(336)), ymax = mean +((1.96*sd)/sqrt(336)))) +
    geom_col(fill = "gray") +
    geom_errorbar() +
    theme_bw() +
    xlab("Grade Level") +
    ylab("Mean TETC value") +
    theme(text = element_text(size = 18)) +
    scale_x_discrete(labels = c("Elementary (n = 58)", 
                                "Secondary (n = 76)",
                                "Other (n = 47)",
                                "All (n = 156)")) +
    xlab(NULL) + 
    coord_flip()

sg

ggsave("grade-plot-1.png", width = 6, height = 5)
```

## Content area/subject

```{r}
d %>%
    count(Q8) %>% 
    arrange(desc(n)) %>% 
    write_csv("subject.csv")

m <- read_csv("subject-m.csv")
m <- m %>% set_names(c("Q8", "Q8n", "Q8_code")) %>% mutate(Q8_code = ifelse(Q8_code == "STEM", "Science and Math", Q8_code))

d <- d %>% left_join(m, by = "Q8")

dd <- d %>% select(v1:v12, Q8_code)
c <- cbind(dd[, 1:12])
m <- manova(as.matrix(c) ~ dd$Q8_code)
summary(m)

d %>% 
    select(v1:v12) %>% 
    map(~ aov(. ~ d$Q8_code)) %>% 
    map_df(tidy) %>% 
    filter(term != "Residuals") %>% 
    mutate(var = str_c("v", 1:12)) %>% 
    select(var, sumsq, statistic, p.value) %>% 
    mutate(p.value_adj = p.adjust(p.value, method = "hochberg")) %>% 
    mutate_if(is.numeric, round, 3)

d %>% 
    select(v1:v12) %>% 
    map(~ aov(. ~ d$Q8_code)) %>% 
    map(TukeyHSD) %>% 
    map_df(tidy) %>% 
    mutate(var = rep(1:12, each = 6)) %>% 
    mutate_if(is.numeric, round, 3) %>% 
    mutate(est_p = ifelse(adj.p.value < .001, str_c(estimate, "***"),
                          ifelse(adj.p.value < .01, str_c(estimate, "**"),
                                 ifelse(adj.p.value < .05, str_c(estimate, "*"), estimate)))) %>% 
    select(var, comparison, est_p) %>% 
    spread(comparison, est_p) %>%
    write_csv("subject-tukey.csv")

dm <- d %>% 
    select(Q8_code, v1:v12) %>% 
    gather(key, val, -Q8_code)

x <- aov(val ~ Q8_code, data = dm)
summary(aov(val ~ Q8_code, data = dm))

TukeyHSD(x) %>% 
    pluck(1) %>% 
    as.data.frame() %>% 
    rownames_to_column("comparison")

TukeyHSD(x)

dm %>% group_by(Q8_code) %>% summarize(mean_val = mean(val, na.rm = T), sd_val = sd(val, na.rm = TRUE))

sp <- d %>% 
    select(Q8_code, v1:v12) %>% 
    filter(!is.na(Q8_code)) %>% 
    gather(key, val, -Q8_code) %>% 
    group_by(Q8_code) %>% 
    summarize(mean = mean(val, na.rm = TRUE),
              sd = sd(val, na.rm = TRUE)) %>% 
    ggplot(aes(x = reorder(Q8_code, mean), y = mean)) +
    theme_bw() +
    geom_col(fill = "gray") +
    geom_errorbar(aes(ymin = mean - ((1.96*sd)/sqrt(336)), ymax = mean +((1.96*sd)/sqrt(336)))) +
    xlab("Subject") +
    ylab("Mean TETC value") +
    theme(text = element_text(size = 18)) +
    scale_x_discrete(labels = c("Humanities & Spec. Ed. (n = 97)", 
                                "Science & Math (n = 73)",
                                "Other (n = 78)",
                                "Technology (n = 42)")) +
    xlab(NULL) + 
    coord_flip()

sp

ggsave("subject-plot.png", width = 7, height = 5)
```

```{r}
sg + sp + plot_layout(nrow = 1, ncol = 2, heights = 1, 1.15)
ggsave("combined-plot.png", width = 12, height = 7)
```